export interface Major {
  name: string;
  category: string;
}

export interface University {
  id: string;
  name: string;
  type: 'National' | 'LAC';
  location: string;
  lat: number;
  lng: number;
  sfRatio: number;
  acceptanceRate: number;
  undergradEnrollment: number;
  totalStudents: number;
  tuitionLocal: number;
  tuitionIntl: number;
  endowment: string;
  website: string;
  motto: string;
  vibe: string;
  special: string;
  image: string;
  logo: string;
  ranking: number;
  majors: Major[];
}

export const UNIVERSITIES: University[] = [
  {
    id: 'princeton',
    name: 'Princeton University',
    type: 'National',
    location: 'Princeton, NJ',
    lat: 40.3431,
    lng: -74.6551,
    sfRatio: 5,
    acceptanceRate: 4,
    undergradEnrollment: 5321,
    totalStudents: 8478,
    tuitionLocal: 59710,
    tuitionIntl: 59710,
    endowment: '35.8',
    website: 'https://www.princeton.edu',
    motto: 'Dei Sub Numine Viget (Under God\'s Power She Flourishes)',
    vibe: 'Intellectual, traditional, residential, close-knit campus life.',
    special: 'Senior Thesis requirement for all students; no professional schools (Law/Med/Business).',
    image: 'https://images.unsplash.com/photo-1610444583737-233ed98328c6?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Princeton_seal.svg',
    ranking: 1,
    majors: [
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Public and International Affairs', category: 'SPIA' },
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'Physics', category: 'Natural Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Architecture', category: 'Arts' },
      { name: 'Astrophysical Sciences', category: 'Natural Sciences' },
      { name: 'Chemical and Biological Engineering', category: 'Engineering' },
      { name: 'Civil and Environmental Engineering', category: 'Engineering' },
      { name: 'Comparative Literature', category: 'Humanities' },
      { name: 'Electrical and Computer Engineering', category: 'Engineering' },
      { name: 'Mechanical and Aerospace Engineering', category: 'Engineering' },
      { name: 'Molecular Biology', category: 'Natural Sciences' },
      { name: 'Neuroscience', category: 'Natural Sciences' },
      { name: 'Operations Research and Financial Engineering', category: 'Engineering' },
      { name: 'Philosophy', category: 'Humanities' },
      { name: 'Politics', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'Sociology', category: 'Social Sciences' }
    ]
  },
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    type: 'National',
    location: 'Cambridge, MA',
    lat: 42.3601,
    lng: -71.0942,
    sfRatio: 3,
    acceptanceRate: 4,
    undergradEnrollment: 4638,
    totalStudents: 11934,
    tuitionLocal: 59750,
    tuitionIntl: 59750,
    endowment: '24.6',
    website: 'https://www.mit.edu',
    motto: 'Mens et Manus (Mind and Hand)',
    vibe: 'Collaborative, high-pressure, inventive, quirky, STEM-focused.',
    special: 'The "UROP" program (Undergraduate Research Opportunity); famous "Hacks" (pranks).',
    image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/MIT_logo.svg',
    ranking: 2,
    majors: [
      { name: 'Electrical Engineering and Computer Science', category: 'Engineering' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Mathematics', category: 'Sciences' },
      { name: 'Physics', category: 'Sciences' },
      { name: 'Biology', category: 'Sciences' },
      { name: 'Aerospace Engineering', category: 'Engineering' },
      { name: 'Chemical Engineering', category: 'Engineering' },
      { name: 'Biological Engineering', category: 'Engineering' },
      { name: 'Civil and Environmental Engineering', category: 'Engineering' },
      { name: 'Economics', category: 'Humanities & Social Sciences' },
      { name: 'Management', category: 'Sloan School' },
      { name: 'Brain and Cognitive Sciences', category: 'Sciences' },
      { name: 'Nuclear Science and Engineering', category: 'Engineering' },
      { name: 'Architecture', category: 'Architecture & Planning' },
      { name: 'Materials Science and Engineering', category: 'Engineering' },
      { name: 'Music and Theater Arts', category: 'Humanities & Social Sciences' },
      { name: 'Linguistics and Philosophy', category: 'Humanities & Social Sciences' },
      { name: 'Political Science', category: 'Humanities & Social Sciences' }
    ]
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    type: 'National',
    location: 'Cambridge, MA',
    lat: 42.3770,
    lng: -71.1167,
    sfRatio: 7,
    acceptanceRate: 3.4,
    undergradEnrollment: 7153,
    totalStudents: 25261,
    tuitionLocal: 54269,
    tuitionIntl: 54269,
    endowment: '50.7',
    website: 'https://www.harvard.edu',
    motto: 'Veritas (Truth)',
    vibe: 'Prestigious, high-achieving, diverse, resource-rich.',
    special: 'Residential House system; world\'s largest academic library system.',
    image: 'https://images.unsplash.com/photo-1621356770248-18e0018dc60b?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Harvard_University_coat_of_arms.svg',
    ranking: 3,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Engineering & Applied Sciences' },
      { name: 'Government', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Applied Mathematics', category: 'Engineering & Applied Sciences' },
      { name: 'Molecular and Cellular Biology', category: 'Sciences' },
      { name: 'Neurological Sciences', category: 'Sciences' },
      { name: 'History', category: 'Social Sciences' },
      { name: 'Art, Film, and Visual Studies', category: 'Arts & Humanities' },
      { name: 'Biomedical Engineering', category: 'Engineering & Applied Sciences' },
      { name: 'Social Studies', category: 'Interdisciplinary' },
      { name: 'Environmental Science and Public Policy', category: 'Interdisciplinary' },
      { name: 'Comparative Literature', category: 'Arts & Humanities' },
      { name: 'Statistics', category: 'Sciences' },
      { name: 'Philosophy', category: 'Arts & Humanities' },
      { name: 'English', category: 'Arts & Humanities' },
      { name: 'East Asian Studies', category: 'Social Sciences' },
      { name: 'Germanic Languages and Literatures', category: 'Arts & Humanities' }
    ]
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    type: 'National',
    location: 'Stanford, CA',
    lat: 37.4275,
    lng: -122.1697,
    sfRatio: 5,
    acceptanceRate: 3.9,
    undergradEnrollment: 7644,
    totalStudents: 17326,
    tuitionLocal: 61731,
    tuitionIntl: 61731,
    endowment: '36.3',
    website: 'https://www.stanford.edu',
    motto: 'Die Luft der Freiheit weht (The wind of freedom blows)',
    vibe: 'Entrepreneurial, relaxed "Palo Alto" feel, outdoorsy, multidisciplinary.',
    special: 'Proximity to Silicon Valley; exceptional D1 sports alongside academics.',
    image: 'https://images.unsplash.com/photo-1511216113906-8f57bb83e776?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Stanford_University_seal.svg',
    ranking: 4,
    majors: [
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Human Biology', category: 'Humanities & Sciences' },
      { name: 'Economics', category: 'Humanities & Sciences' },
      { name: 'Management Science & Engineering', category: 'Engineering' },
      { name: 'Electrical Engineering', category: 'Engineering' },
      { name: 'Political Science', category: 'Humanities & Sciences' }
    ]
  },
  {
    id: 'yale',
    name: 'Yale University',
    type: 'National',
    location: 'New Haven, CT',
    lat: 41.3163,
    lng: -72.9223,
    sfRatio: 6,
    acceptanceRate: 4.4,
    undergradEnrollment: 6590,
    totalStudents: 14567,
    tuitionLocal: 64700,
    tuitionIntl: 64700,
    endowment: '40.7',
    website: 'https://www.yale.edu',
    motto: 'Lux et Veritas (Light and Truth)',
    vibe: 'Gothic architecture, creative, passionate, strong undergraduate focus.',
    special: 'Yale School of Drama and School of Music; 14 residential colleges.',
    image: 'https://images.unsplash.com/photo-1629112435552-3be9f395da60?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Yale_University_Shield_1.svg',
    ranking: 5,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Engineering & Applied Science' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Ethics, Politics, and Economics (EPE)', category: 'Interdisciplinary' },
      { name: 'Global Affairs', category: 'Social Sciences' },
      { name: 'Molecular, Cellular, and Developmental Biology', category: 'Sciences' },
      { name: 'Neuroscience', category: 'Sciences' },
      { name: 'Architecture', category: 'Arts' },
      { name: 'Cognitive Science', category: 'Social Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'History of Art', category: 'Humanities' },
      { name: 'Environmental Studies', category: 'Interdisciplinary' },
      { name: 'Statistics and Data Science', category: 'Sciences' },
      { name: 'Humanities', category: 'Humanities' },
      { name: 'East Asian Studies', category: 'Humanities' }
    ]
  },
  {
    id: 'upenn',
    name: 'University of Pennsylvania',
    type: 'National',
    location: 'Philadelphia, PA',
    lat: 39.9522,
    lng: -75.1932,
    sfRatio: 6,
    acceptanceRate: 6,
    undergradEnrollment: 10412,
    totalStudents: 28038,
    tuitionLocal: 66104,
    tuitionIntl: 66104,
    endowment: '21.0',
    website: 'https://www.upenn.edu',
    motto: 'Leges sine moribus vanae (Laws without morals are useless)',
    vibe: 'Pre-professional, energetic, urban, work-hard-play-hard.',
    special: 'Wharton School of Business; the "One University" policy (easy cross-disciplinary study).',
    image: 'https://images.unsplash.com/photo-1582213717521-4ea2e069152a?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/92/UPenn_shield_with_motto.svg',
    ranking: 6,
    majors: [
      { name: 'Finance', category: 'Wharton' },
      { name: 'Nursing', category: 'Nursing' },
      { name: 'Economics', category: 'Arts & Sciences' },
      { name: 'Political Science', category: 'Arts & Sciences' },
      { name: 'Computer Science', category: 'Engineering & Applied Science' },
      { name: 'Marketing', category: 'Wharton' }
    ]
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    type: 'National',
    location: 'Pasadena, CA',
    lat: 34.1376,
    lng: -118.1253,
    sfRatio: 3,
    acceptanceRate: 3.9,
    undergradEnrollment: 987,
    totalStudents: 2397,
    tuitionLocal: 60864,
    tuitionIntl: 60864,
    endowment: '3.6',
    website: 'https://www.caltech.edu',
    motto: 'The truth shall make you free',
    vibe: 'Intense, tiny, rigorous, scientifically driven.',
    special: 'Manages NASA\'s Jet Propulsion Laboratory; honor code is everything.',
    image: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/California_Institute_of_Technology_seal.svg',
    ranking: 7,
    majors: [
      { name: 'Physics', category: 'Physics, Mathematics & Astronomy' },
      { name: 'Computer Science', category: 'Engineering & Applied Science' },
      { name: 'Mechanical Engineering', category: 'Engineering & Applied Science' },
      { name: 'Mathematics', category: 'Physics, Mathematics & Astronomy' },
      { name: 'Chemistry', category: 'Chemistry & Chemical Engineering' }
    ]
  },
  {
    id: 'duke',
    name: 'Duke University',
    type: 'National',
    location: 'Durham, NC',
    lat: 36.0014,
    lng: -78.9382,
    sfRatio: 6,
    acceptanceRate: 6,
    undergradEnrollment: 6883,
    totalStudents: 16780,
    tuitionLocal: 63054,
    tuitionIntl: 63054,
    endowment: '12.1',
    website: 'https://www.duke.edu',
    motto: 'Eruditio et Religio (Knowledge and Faith)',
    vibe: 'Spirited, athletic (basketball!), gothic, high-energy.',
    special: 'Duke Gardens; strong collaboration between medical and engineering schools.',
    image: 'https://images.unsplash.com/photo-1629814407553-7313a968662d?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Duke_University_seal.svg',
    ranking: 7,
    majors: [
      { name: 'Computer Science', category: 'Arts & Sciences' },
      { name: 'Public Policy Analysis', category: 'Sanford School of Public Policy' },
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Biomedical Engineering', category: 'Pratt School of Engineering' }
    ]
  },
  {
    id: 'uchicago',
    name: 'University of Chicago',
    type: 'National',
    location: 'Chicago, IL',
    lat: 41.7886,
    lng: -87.5987,
    sfRatio: 5,
    acceptanceRate: 5,
    undergradEnrollment: 7153,
    totalStudents: 18458,
    tuitionLocal: 64260,
    tuitionIntl: 64260,
    endowment: '11.0',
    website: 'https://www.uchicago.edu',
    motto: 'Crescat scientia; vita excolatur',
    vibe: 'Intellectual, debate-driven, rigourous.',
    special: 'The "Common Core" curriculum; Scav hunt.',
    image: 'https://images.unsplash.com/photo-1605333116900-34446b149b15?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/University_of_Chicago_coat_of_arms.svg',
    ranking: 11,
    majors: [
      { name: 'Economics', category: 'The College' },
      { name: 'Computer Science', category: 'The College' },
      { name: 'Mathematics', category: 'The College' },
      { name: 'Political Science', category: 'The College' },
      { name: 'Public Policy', category: 'The College' },
      { name: 'Biology', category: 'The College' },
      { name: 'Psychology', category: 'The College' },
      { name: 'Sociology', category: 'The College' },
      { name: 'History', category: 'The College' },
      { name: 'Physics', category: 'The College' },
      { name: 'Philosophical Aspects of Social Action', category: 'The College' }
    ]
  },
  {
    id: 'berkeley',
    name: 'University of California, Berkeley',
    type: 'National',
    location: 'Berkeley, CA',
    lat: 37.8715,
    lng: -122.2730,
    sfRatio: 17,
    acceptanceRate: 11,
    undergradEnrollment: 32831,
    totalStudents: 45307,
    tuitionLocal: 15444,
    tuitionIntl: 48465,
    endowment: '6.9',
    website: 'https://www.berkeley.edu',
    motto: 'Fiat Lux (Let There Be Light)',
    vibe: 'Socially conscious, diverse, massive, competitive.',
    special: 'Birthplace of the Free Speech Movement; top public university.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Seal_of_University_of_California%2C_Berkeley.svg',
    ranking: 15,
    majors: [
      { name: 'Computer Science', category: 'Engineering / Letters & Science' },
      { name: 'Economics', category: 'Letters & Science' },
      { name: 'Molecular and Cell Biology', category: 'Letters & Science' },
      { name: 'Business Administration', category: 'Haas School of Business' },
      { name: 'Political Science', category: 'Letters & Science' },
      { name: 'Psychology', category: 'Letters & Science' },
      { name: 'English', category: 'Letters & Science' },
      { name: 'Architecture', category: 'Environmental Design' },
      { name: 'Chemical Engineering', category: 'Chemistry' },
      { name: 'Interdisciplinary Studies', category: 'Letters & Science' }
    ]
  },
  {
    id: 'ucla',
    name: 'University of California, Los Angeles',
    type: 'National',
    location: 'Los Angeles, CA',
    lat: 34.0689,
    lng: -118.4452,
    sfRatio: 18,
    acceptanceRate: 9,
    undergradEnrollment: 31633,
    totalStudents: 46116,
    tuitionLocal: 15152,
    tuitionIntl: 47684,
    endowment: '7.8',
    website: 'https://www.ucla.edu',
    motto: 'Fiat Lux (Let There Be Light)',
    vibe: 'Vibrant, athletic, urban luxury, competitive.',
    special: 'Most applied-to university in the nation; legendary sports history.',
    image: 'https://images.unsplash.com/photo-1559135197-8a45ea74d12c?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ed/UCLA_seal.svg',
    ranking: 15,
    majors: [
      { name: 'Biology', category: 'College of Letters and Science' },
      { name: 'Political Science', category: 'College of Letters and Science' },
      { name: 'Psychology', category: 'College of Letters and Science' },
      { name: 'Economics', category: 'College of Letters and Science' },
      { name: 'Computer Science', category: 'Samueli School of Engineering' },
      { name: 'Business Economics', category: 'College of Letters and Science' },
      { name: 'Mathematics', category: 'College of Letters and Science' },
      { name: 'Aerospace Engineering', category: 'Samueli School of Engineering' },
      { name: 'English', category: 'College of Letters and Science' },
      { name: 'History', category: 'College of Letters and Science' }
    ]
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    type: 'National',
    location: 'Ithaca, NY',
    lat: 42.4485,
    lng: -76.4735,
    sfRatio: 9,
    acceptanceRate: 8,
    undergradEnrollment: 15503,
    totalStudents: 25582,
    tuitionLocal: 65204,
    tuitionIntl: 65204,
    endowment: '10.0',
    website: 'https://www.cornell.edu',
    motto: 'I would found an institution where any person can find instruction in any study',
    vibe: 'Gorges, balanced, eclectic, rigorous.',
    special: 'The Hotel School; unique combination of private and state-contracted colleges.',
    image: 'https://images.unsplash.com/photo-1596781295982-f567b4507f35?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Cornell_University_seal.svg',
    ranking: 12,
    majors: [
      { name: 'Computer Science', category: 'Computing and Information Science' },
      { name: 'Biology', category: 'Agriculture and Life Sciences' },
      { name: 'Hotel Administration', category: 'Nolan School of Hotel Administration' },
      { name: 'Labor and Industrial Relations', category: 'ILR School' },
      { name: 'Applied Economics and Management', category: 'Dyson School' },
      { name: 'Architecture', category: 'AAP' },
      { name: 'Agricultural Sciences', category: 'Agriculture and Life Sciences' },
      { name: 'Civil Engineering', category: 'Engineering' },
      { name: 'English', category: 'Arts and Sciences' },
      { name: 'Fiber Science & Apparel Design', category: 'Human Ecology' },
      { name: 'Government', category: 'Arts and Sciences' },
      { name: 'Information Science', category: 'Computing and Information Science' },
      { name: 'Mechanical Engineering', category: 'Engineering' }
    ]
  },

  // LACs
  {
    id: 'williams',
    name: 'Williams College',
    type: 'LAC',
    location: 'Williamstown, MA',
    lat: 42.7118,
    lng: -73.2043,
    sfRatio: 7,
    acceptanceRate: 10,
    undergradEnrollment: 2129,
    totalStudents: 2216,
    tuitionLocal: 64860,
    tuitionIntl: 64860,
    endowment: '3.5',
    website: 'https://www.williams.edu',
    motto: 'E Liberalitate (Through Generosity)',
    vibe: 'Rural, elite, close faculty contact, mountain views.',
    special: 'Tutorial system modeled after Oxford and Cambridge; #1 LAC.',
    image: 'https://images.unsplash.com/photo-1621356770248-18e0018dc60b?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c9/Williams_College_seal.svg',
    ranking: 1,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'amherst',
    name: 'Amherst College',
    type: 'LAC',
    location: 'Amherst, MA',
    lat: 42.3709,
    lng: -72.5170,
    sfRatio: 7,
    acceptanceRate: 9,
    undergradEnrollment: 1971,
    totalStudents: 1971,
    tuitionLocal: 66650,
    tuitionIntl: 66650,
    endowment: '3.3',
    website: 'https://www.amherst.edu',
    motto: 'Terras Irradient (Let them enlighten the lands)',
    vibe: 'Open curriculum, intellectual, progressive.',
    special: 'Five College Consortium access; no core curriculum requirements.',
    image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/2/25/Amherst_College_seal.svg',
    ranking: 2,
    majors: [
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' }
    ]
  },
  {
    id: 'swarthmore',
    name: 'Swarthmore College',
    type: 'LAC',
    location: 'Swarthmore, PA',
    lat: 39.9048,
    lng: -75.3547,
    sfRatio: 8,
    acceptanceRate: 7,
    undergradEnrollment: 1689,
    totalStudents: 1689,
    tuitionLocal: 62412,
    tuitionIntl: 62412,
    endowment: '2.7',
    website: 'https://www.swarthmore.edu',
    motto: 'Mind the Light',
    vibe: 'Serious, Quaker roots, social justice focused.',
    special: 'External Examination Program for Honors.',
    image: 'https://images.unsplash.com/photo-1582213717521-4ea2e069152a?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Swarthmore_College_seal.svg',
    ranking: 3,
    majors: [
      { name: 'Mathematics & Statistics', category: 'Natural Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Engineering & Natural Sciences' }
    ]
  },
  {
    id: 'pomona',
    name: 'Pomona College',
    type: 'LAC',
    location: 'Claremont, CA',
    lat: 34.0984,
    lng: -117.7126,
    sfRatio: 7,
    acceptanceRate: 7,
    undergradEnrollment: 1740,
    totalStudents: 1740,
    tuitionLocal: 61906,
    tuitionIntl: 61906,
    endowment: '2.8',
    website: 'https://www.pomona.edu',
    motto: 'Our Tribute to Christian Civilization',
    vibe: 'Sunny, collaborative, Southern California lifestyle.',
    special: 'The "Claremont Colleges" 5C consortium.',
    image: 'https://images.unsplash.com/photo-1511216113906-8f57bb83e776?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Pomona_College_seal.svg',
    ranking: 4,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Natural Sciences' },
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'Molecular Biology', category: 'Natural Sciences' },
      { name: 'Politics', category: 'Social Sciences' }
    ]
  },
  {
    id: 'wellesley',
    name: 'Wellesley College',
    type: 'LAC',
    location: 'Wellesley, MA',
    lat: 42.2968,
    lng: -71.3031,
    sfRatio: 7,
    acceptanceRate: 13,
    undergradEnrollment: 2461,
    totalStudents: 2461,
    tuitionLocal: 64140,
    tuitionIntl: 64140,
    endowment: '3.2',
    website: 'https://www.wellesley.edu',
    motto: 'Non Ministrari sed Ministrare (Not to be ministered unto, but to minister)',
    vibe: 'Empowering, academic excellence, scenic lakefront campus.',
    special: 'Historic women\'s college; cross-registration with MIT.',
    image: 'https://images.unsplash.com/photo-1621356770248-18e0018dc60b?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Wellesley_College_seal.svg',
    ranking: 5,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Biological Sciences', category: 'Natural Sciences' },
      { name: 'Computer Science', category: 'Natural Sciences' },
      { name: 'Psychology', category: 'Social Sciences' }
    ]
  },
  {
    id: 'brown',
    name: 'Brown University',
    type: 'National',
    location: 'Providence, RI',
    lat: 41.8268,
    lng: -71.4025,
    sfRatio: 6,
    acceptanceRate: 5,
    undergradEnrollment: 7125,
    totalStudents: 10425,
    tuitionLocal: 65656,
    tuitionIntl: 65656,
    endowment: '6.5',
    website: 'https://www.brown.edu',
    motto: 'In Deo Speramus (In God We Hope)',
    vibe: 'Independent, creative, progressive, academic freedom.',
    special: 'The Open Curriculum; choose-your-own-adventure education.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/a/ac/Brown_University_coat_of_arms.svg',
    ranking: 9,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Physical Sciences' },
      { name: 'Biology', category: 'Biological Sciences' },
      { name: 'International Relations', category: 'Social Sciences' },
      { name: 'Engineering', category: 'Engineering' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Cognitive Science', category: 'Sciences' },
      { name: 'Mathematics', category: 'Sciences' },
      { name: 'Public Health', category: 'Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Literary Arts', category: 'Arts' },
      { name: 'Applied Mathematics', category: 'Sciences' },
      { name: 'Geology-Physics/Mathematics', category: 'Sciences' },
      { name: 'Modern Culture and Media', category: 'Arts & Humanities' }
    ]
  },
  {
    id: 'jhu',
    name: 'Johns Hopkins University',
    type: 'National',
    location: 'Baltimore, MD',
    lat: 39.3299,
    lng: -76.6205,
    sfRatio: 6,
    acceptanceRate: 7,
    undergradEnrollment: 6132,
    totalStudents: 31275,
    tuitionLocal: 62840,
    tuitionIntl: 62840,
    endowment: '10.5',
    website: 'https://www.jhu.edu',
    motto: 'Veritas vos liberabit (The truth shall set you free)',
    vibe: 'Research-heavy, pre-med focus, rigorous, innovative.',
    special: 'The nation\'s first research university; Bloomberg School of Public Health.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/2/23/Johns_Hopkins_University_seal.svg',
    ranking: 9,
    majors: [
      { name: 'Biomedical Engineering', category: 'Whiting School of Engineering' },
      { name: 'Molecular & Cellular Biology', category: 'Krieger School of Arts & Sciences' },
      { name: 'Neuroscience', category: 'Krieger School of Arts & Sciences' },
      { name: 'Public Health', category: 'Krieger School of Arts & Sciences' },
      { name: 'Computer Science', category: 'Whiting School of Engineering' },
      { name: 'International Studies', category: 'Krieger School of Arts & Sciences' },
      { name: 'Mechanical Engineering', category: 'Whiting School of Engineering' },
      { name: 'Applied Mathematics and Statistics', category: 'Whiting School of Engineering' },
      { name: 'Chemical and Biomolecular Engineering', category: 'Whiting School of Engineering' },
      { name: 'Cognitive Science', category: 'Krieger School of Arts & Sciences' },
      { name: 'Economics', category: 'Krieger School of Arts & Sciences' },
      { name: 'Psychology', category: 'Krieger School of Arts & Sciences' }
    ]
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    type: 'National',
    location: 'Evanston, IL',
    lat: 42.0565,
    lng: -87.6753,
    sfRatio: 6,
    acceptanceRate: 7,
    undergradEnrollment: 8494,
    totalStudents: 22617,
    tuitionLocal: 64887,
    tuitionIntl: 64887,
    endowment: '14.1',
    website: 'https://www.northwestern.edu',
    motto: 'Quaecumque sunt vera (Whatsoever things are true)',
    vibe: 'Collaborative, purple-pride, pre-professional but creative.',
    special: 'Medill School of Journalism; Kellogg School of Management.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Northwestern_University_seal.svg',
    ranking: 9,
    majors: [
      { name: 'Journalism', category: 'Medill' },
      { name: 'Economics', category: 'Weinberg' },
      { name: 'Psychology', category: 'Weinberg' },
      { name: 'Computer Science', category: 'McCormick Engineering' },
      { name: 'Theatre', category: 'School of Communication' },
      { name: 'Radio/Television/Film', category: 'School of Communication' },
      { name: 'Biological Sciences', category: 'Weinberg' },
      { name: 'Political Science', category: 'Weinberg' },
      { name: 'Industrial Engineering and Management Sciences', category: 'McCormick Engineering' },
      { name: 'Mechanical Engineering', category: 'McCormick Engineering' },
      { name: 'Social Policy', category: 'SESP' }
    ]
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    type: 'National',
    location: 'New York, NY',
    lat: 40.8075,
    lng: -73.9626,
    sfRatio: 6,
    acceptanceRate: 4,
    undergradEnrollment: 8840,
    totalStudents: 33777,
    tuitionLocal: 68400,
    tuitionIntl: 68400,
    endowment: '13.3',
    website: 'https://www.columbia.edu',
    motto: 'In lumine Tuo videbimus lumen (In Thy light shall we see light)',
    vibe: 'Urban, intellectual, fast-paced, core-focused.',
    special: 'The Core Curriculum; Manhattanville expansion.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Columbia_University_seal.svg',
    ranking: 12,
    majors: [
      { name: 'Political Science', category: 'Columbia College' },
      { name: 'Economics', category: 'Columbia College' },
      { name: 'Computer Science', category: 'Engineering & Applied Science' },
      { name: 'History', category: 'Columbia College' },
      { name: 'English', category: 'Columbia College' },
      { name: 'Financial Economics', category: 'Columbia College' },
      { name: 'Sociology', category: 'Columbia College' },
      { name: 'Mathematics-Statistics', category: 'Columbia College' },
      { name: 'Neuroscience and Behavior', category: 'Columbia College' },
      { name: 'Civil Engineering', category: 'Engineering & Applied Science' },
      { name: 'Industrial Engineering and Operations Research', category: 'Engineering & Applied Science' }
    ]
  },
  {
    id: 'bowdoin',
    name: 'Bowdoin College',
    type: 'LAC',
    location: 'Brunswick, ME',
    lat: 43.9077,
    lng: -69.9631,
    sfRatio: 9,
    acceptanceRate: 9,
    undergradEnrollment: 1915,
    totalStudents: 1915,
    tuitionLocal: 61528,
    tuitionIntl: 61528,
    endowment: '2.4',
    website: 'https://www.bowdoin.edu',
    motto: 'Ut aquila versus coelum (As an eagle towards the sky)',
    vibe: 'Coastal, friendly, seafood-loving, community-oriented.',
    special: 'First college in the U.S. to go test-optional (1969).',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Bowdoin_College_seal.svg',
    ranking: 6,
    majors: [
      { name: 'Government & Legal Studies', category: 'Social Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'History', category: 'Humanities' }
    ]
  },
  {
    id: 'carleton',
    name: 'Carleton College',
    type: 'LAC',
    location: 'Northfield, MN',
    lat: 44.4612,
    lng: -93.1539,
    sfRatio: 8,
    acceptanceRate: 17,
    undergradEnrollment: 2044,
    totalStudents: 2044,
    tuitionLocal: 65457,
    tuitionIntl: 65457,
    endowment: '1.1',
    website: 'https://www.carleton.edu',
    motto: 'Illuminat (It illuminates)',
    vibe: 'Quirky, academic, Midwest-nice, intellectual.',
    special: 'Trimester system; "Friday Flowers" tradition.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Carleton_College_seal.svg',
    ranking: 6,
    majors: [
      { name: 'Computer Science', category: 'Mathematics & Natural Sciences' },
      { name: 'Biology', category: 'Mathematics & Natural Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Psychology', category: 'Social Sciences' }
    ]
  },
  {
    id: 'cmc',
    name: 'Claremont McKenna College',
    type: 'LAC',
    location: 'Claremont, CA',
    lat: 34.1017,
    lng: -117.7088,
    sfRatio: 8,
    acceptanceRate: 10,
    undergradEnrollment: 1380,
    totalStudents: 1380,
    tuitionLocal: 60715,
    tuitionIntl: 60715,
    endowment: '1.2',
    website: 'https://www.cmc.edu',
    motto: 'Crescit cum commercio civitas (Civilization prospers with commerce)',
    vibe: 'Leadership-focused, athletic, conservative-leaning but balanced.',
    special: 'Strong emphasis on public affairs, economics, and business.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Claremont_McKenna_College_seal.svg',
    ranking: 6,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Government', category: 'Social Sciences' },
      { name: 'International Relations', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Philosophy', category: 'Humanities' }
    ]
  },
  {
    id: 'dartmouth',
    name: 'Dartmouth College',
    type: 'National',
    location: 'Hanover, NH',
    lat: 43.7022,
    lng: -72.2896,
    sfRatio: 7,
    acceptanceRate: 6,
    undergradEnrollment: 4458,
    totalStudents: 6761,
    tuitionLocal: 63684,
    tuitionIntl: 63684,
    endowment: '8.1',
    website: 'https://www.dartmouth.edu',
    motto: 'Vox clamantis in deserto (A voice crying in the wilderness)',
    vibe: 'Outdoorsy, spirited, community-focused, rustic but elite.',
    special: 'The "D-Plan" (flexible year-round quarter system); first Ivy to go needs-blind for intl.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e4/Dartmouth_College_shield.svg',
    ranking: 18,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Government', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Sciences' },
      { name: 'Engineering Sciences', category: 'Engineering' },
      { name: 'History', category: 'Humanities' },
      { name: 'Biology', category: 'Sciences' },
      { name: 'Psychology', category: 'Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'Mathematics', category: 'Sciences' },
      { name: 'Philosophy', category: 'Humanities' },
      { name: 'Cognitive Science', category: 'Interdisciplinary' }
    ]
  },
  {
    id: 'vanderbilt',
    name: 'Vanderbilt University',
    type: 'National',
    location: 'Nashville, TN',
    lat: 36.1447,
    lng: -86.8027,
    sfRatio: 7,
    acceptanceRate: 7,
    undergradEnrollment: 7111,
    totalStudents: 13796,
    tuitionLocal: 61618,
    tuitionIntl: 61618,
    endowment: '10.2',
    website: 'https://www.vanderbilt.edu',
    motto: 'Desidia Paullatim Evocetur (Let idleness be gradually called away)',
    vibe: 'Balanced, Southern charm, urban, collaborative.',
    special: 'The Blair School of Music; Peabody College of Education.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Vanderbilt_University_seal.svg',
    ranking: 18,
    majors: [
      { name: 'Economics', category: 'Arts & Science' },
      { name: 'Human & Organizational Development', category: 'Peabody College' },
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Political Science', category: 'Arts & Science' },
      { name: 'Biological Sciences', category: 'Arts & Science' },
      { name: 'Blair School: Musical Performance', category: 'Blair School of Music' },
      { name: 'Child Development', category: 'Peabody College' },
      { name: 'Cognitive Studies', category: 'Peabody College' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Neuroscience', category: 'Arts & Science' },
      { name: 'Medicine, Health, & Society', category: 'Arts & Science' }
    ]
  },
  {
    id: 'rice',
    name: 'Rice University',
    type: 'National',
    location: 'Houston, TX',
    lat: 29.7174,
    lng: -95.4018,
    sfRatio: 6,
    acceptanceRate: 9,
    undergradEnrollment: 4480,
    totalStudents: 8565,
    tuitionLocal: 57210,
    tuitionIntl: 57210,
    endowment: '8.1',
    website: 'https://www.rice.edu',
    motto: 'Letters, Science, Art',
    vibe: 'Collaborative, quirky, diverse, residential college system.',
    special: 'The Shepherd School of Music; Baker Institute for Public Policy.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Rice_University_seal.svg',
    ranking: 17,
    majors: [
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Cognitive Sciences', category: 'Social Sciences' },
      { name: 'Bioengineering', category: 'Engineering' },
      { name: 'Architecture', category: 'Architecture' },
      { name: 'Music', category: 'Shepherd School of Music' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Ancient Mediterranean Civilizations', category: 'Humanities' }
    ]
  },
  {
    id: 'notredame',
    name: 'University of Notre Dame',
    type: 'National',
    location: 'Notre Dame, IN',
    lat: 41.7022,
    lng: -86.2353,
    sfRatio: 9,
    acceptanceRate: 12,
    undergradEnrollment: 8973,
    totalStudents: 13139,
    tuitionLocal: 62693,
    tuitionIntl: 62693,
    endowment: '20.3',
    website: 'https://www.nd.edu',
    motto: 'Vita Dulcedo Spes (Life, Sweetness, Hope)',
    vibe: 'Spirited, traditional, faith-inspired, tight community.',
    special: 'The Golden Dome; legendary football tradition; Mendoza College of Business.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/0/03/University_of_Notre_Dame_seal.svg',
    ranking: 20,
    majors: [
      { name: 'Finance', category: 'Mendoza' },
      { name: 'Accounting', category: 'Mendoza' },
      { name: 'Economics', category: 'Arts & Letters' },
      { name: 'Political Science', category: 'Arts & Letters' },
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Marketing', category: 'Mendoza' },
      { name: 'Management Consulting', category: 'Mendoza' },
      { name: 'Aerospace Engineering', category: 'Engineering' },
      { name: 'Architecture', category: 'School of Architecture' },
      { name: 'Pre-Professional Studies', category: 'Science' }
    ]
  },
  {
    id: 'michigan',
    name: 'University of Michigan',
    type: 'National',
    location: 'Ann Arbor, MI',
    lat: 42.2775,
    lng: -83.7382,
    sfRatio: 15,
    acceptanceRate: 18,
    undergradEnrollment: 32695,
    totalStudents: 51225,
    tuitionLocal: 17786,
    tuitionIntl: 57273,
    endowment: '17.9',
    website: 'https://www.umich.edu',
    motto: 'Artes, Scientia, Veritas (Arts, Knowledge, Truth)',
    vibe: 'Massive, athletic (Go Blue!), academic powerhouse, balanced.',
    special: 'The "Big House"; Ross School of Business; top-tier research across all fields.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Seal_of_the_University_of_Michigan.svg',
    ranking: 21,
    majors: [
      { name: 'Business Administration', category: 'Ross School of Business' },
      { name: 'Computer Science', category: 'Engineering / LSA' },
      { name: 'Economics', category: 'LSA' },
      { name: 'Psychology', category: 'LSA' },
      { name: 'Political Science', category: 'LSA' },
      { name: 'Art and Design', category: 'Stamps School' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Informational Analysis', category: 'School of Information' },
      { name: 'Public Policy', category: 'Ford School' },
      { name: 'Biopsychology, Cognition, and Neuroscience', category: 'LSA' }
    ]
  },
  {
    id: 'middlebury',
    name: 'Middlebury College',
    type: 'LAC',
    location: 'Middlebury, VT',
    lat: 44.0091,
    lng: -73.1760,
    sfRatio: 9,
    acceptanceRate: 13,
    undergradEnrollment: 2855,
    totalStudents: 2855,
    tuitionLocal: 64800,
    tuitionIntl: 64800,
    endowment: '1.5',
    website: 'https://www.middlebury.edu',
    motto: 'Scientia et Virtus (Knowledge and Virtue)',
    vibe: 'Mountainous, environmental, language-focused, rigorous.',
    special: 'Bread Loaf School of English; famous Language Schools.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Middlebury_College_seal.svg',
    ranking: 11,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Environmental Studies', category: 'Interdisciplinary' },
      { name: 'International Studies', category: 'Interdisciplinary' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'haverford',
    name: 'Haverford College',
    type: 'LAC',
    location: 'Haverford, PA',
    lat: 40.0094,
    lng: -75.3052,
    sfRatio: 9,
    acceptanceRate: 14,
    undergradEnrollment: 1420,
    totalStudents: 1420,
    tuitionLocal: 67522,
    tuitionIntl: 67522,
    endowment: '0.6',
    website: 'https://www.haverford.edu',
    motto: 'Non doctior, sed meliore doctrina imbutus (Not more learned, but steeped in better learning)',
    vibe: 'Principal-driven, Honor Code, tight-knit, collaborative.',
    special: 'Student-run Honor Code; part of the Quaker Consortium.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c8/Haverford_College_seal.svg',
    ranking: 11,
    majors: [
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'Political Science', category: 'Social Sciences' }
    ]
  },
  {
    id: 'georgetown',
    name: 'Georgetown University',
    type: 'National',
    location: 'Washington, D.C.',
    lat: 38.9076,
    lng: -77.0723,
    sfRatio: 11,
    acceptanceRate: 12,
    undergradEnrollment: 7500,
    totalStudents: 20000,
    tuitionLocal: 64896,
    tuitionIntl: 64896,
    endowment: '3.2',
    website: 'https://www.georgetown.edu',
    motto: 'Utraque Unum (Both are one)',
    vibe: 'Political, Jesuit, urban, professional, global focus.',
    special: 'Walsh School of Foreign Service; oldest Catholic university in the U.S.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/35/Georgetown_University_seal.svg',
    ranking: 22,
    majors: [
      { name: 'International Politics', category: 'Walsh SFS' },
      { name: 'Finance', category: 'McDonough Business' },
      { name: 'Political Science', category: 'College of Arts & Sciences' },
      { name: 'Economics', category: 'College of Arts & Sciences' },
      { name: 'Nursing', category: 'School of Nursing' }
    ]
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    type: 'National',
    location: 'Pittsburgh, PA',
    lat: 40.4432,
    lng: -79.9428,
    sfRatio: 10,
    acceptanceRate: 11,
    undergradEnrollment: 7000,
    totalStudents: 16000,
    tuitionLocal: 62260,
    tuitionIntl: 62260,
    endowment: '3.0',
    website: 'https://www.cmu.edu',
    motto: 'My heart is in the work',
    vibe: 'Tech-focused, creative, hardworking, interdisciplinary.',
    special: 'World-leading Computer Science and Drama programs; Scott Hall.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Carnegie_Mellon_University_seal.svg',
    ranking: 24,
    majors: [
      { name: 'Computer Science', category: 'School of Computer Science' },
      { name: 'Electrical & Computer Engineering', category: 'College of Engineering' },
      { name: 'Drama', category: 'College of Fine Arts' },
      { name: 'Mechanical Engineering', category: 'College of Engineering' },
      { name: 'Business Administration', category: 'Tepper School of Business' }
    ]
  },
  {
    id: 'emory',
    name: 'Emory University',
    type: 'National',
    location: 'Atlanta, GA',
    lat: 33.7925,
    lng: -84.3247,
    sfRatio: 9,
    acceptanceRate: 11,
    undergradEnrollment: 7100,
    totalStudents: 15400,
    tuitionLocal: 60774,
    tuitionIntl: 60774,
    endowment: '11.0',
    website: 'https://www.emory.edu',
    motto: 'Cor prudentis possidebit scientiam (The wise heart will possess knowledge)',
    vibe: 'Balanced, healthcare-proximate, suburban-urban mix.',
    special: 'Proximity to the CDC; Goizueta Business School.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/36/Emory_University_seal.svg',
    ranking: 24,
    majors: [
      { name: 'Business Administration', category: 'Goizueta Business' },
      { name: 'Biology', category: 'Emory College' },
      { name: 'Psychology', category: 'Emory College' },
      { name: 'Economics', category: 'Emory College' },
      { name: 'Nursing', category: 'School of Nursing' }
    ]
  },
  {
    id: 'uva',
    name: 'University of Virginia',
    type: 'National',
    location: 'Charlottesville, VA',
    lat: 38.0336,
    lng: -78.5080,
    sfRatio: 15,
    acceptanceRate: 19,
    undergradEnrollment: 17500,
    totalStudents: 26000,
    tuitionLocal: 21380,
    tuitionIntl: 56837,
    endowment: '13.6',
    website: 'https://www.virginia.edu',
    motto: 'Artes, Scientia, Veritas (Arts, Knowledge, Truth)',
    vibe: 'Historical, vibrant, "Public Ivy", spirited.',
    special: 'UNESCO World Heritage Site; Jefferson-designed Rotunda.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b1/University_of_Virginia_seal.svg',
    ranking: 24,
    majors: [
      { name: 'Economics', category: 'Arts & Sciences' },
      { name: 'Political Science', category: 'Arts & Sciences' },
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Commerce', category: 'McIntire School' },
      { name: 'Psychology', category: 'Arts & Sciences' }
    ]
  },
  {
    id: 'davidson',
    name: 'Davidson College',
    type: 'LAC',
    location: 'Davidson, NC',
    lat: 35.4988,
    lng: -80.8407,
    sfRatio: 9,
    acceptanceRate: 15,
    undergradEnrollment: 1900,
    totalStudents: 1900,
    tuitionLocal: 60100,
    tuitionIntl: 60100,
    endowment: '1.2',
    website: 'https://www.davidson.edu',
    motto: 'Alenda Lux Ubi Orta Libertas (Let Light Be Nourished Where Liberty Has Arisen)',
    vibe: 'Honor-bound, athletic, intellectual, Southern.',
    special: 'The Davidson Trust (no-loan financial aid); Stephen Curry\'s alma mater.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Davidson_College_seal.svg',
    ranking: 9,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Psychology', category: 'Social Sciences' }
    ]
  },
  {
    id: 'grinnell',
    name: 'Grinnell College',
    type: 'LAC',
    location: 'Grinnell, IA',
    lat: 41.7483,
    lng: -92.7196,
    sfRatio: 9,
    acceptanceRate: 11,
    undergradEnrollment: 1700,
    totalStudents: 1700,
    tuitionLocal: 64800,
    tuitionIntl: 64800,
    endowment: '2.5',
    website: 'https://www.grinnell.edu',
    motto: 'Veritas et Humanitas (Truth and Humanity)',
    vibe: 'Progressive, socially active, rural powerhouse, open curriculum.',
    special: 'One of the largest endowments per student; self-governance policy.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Grinnell_College_seal.svg',
    ranking: 9,
    majors: [
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Computer Science', category: 'Natural Sciences' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Mathematics', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'smith',
    name: 'Smith College',
    type: 'LAC',
    location: 'Northampton, MA',
    lat: 42.3181,
    lng: -72.6381,
    sfRatio: 9,
    acceptanceRate: 19,
    undergradEnrollment: 2100,
    totalStudents: 2600,
    tuitionLocal: 63000,
    tuitionIntl: 63000,
    endowment: '2.5',
    website: 'https://www.smith.edu',
    motto: 'En th aret th gn sin (To virtue, knowledge)',
    vibe: 'Feminist, empowering, historic, scenic.',
    special: 'First women\'s college to offer an engineering degree.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Smith_College_seal.svg',
    ranking: 13,
    majors: [
      { name: 'Engineering', category: 'Engineering' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'Biology', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'washu',
    name: 'Washington University in St. Louis',
    type: 'National',
    location: 'St. Louis, MO',
    lat: 38.6488,
    lng: -90.3108,
    sfRatio: 7,
    acceptanceRate: 11,
    undergradEnrollment: 8100,
    totalStudents: 16500,
    tuitionLocal: 61750,
    tuitionIntl: 61750,
    endowment: '12.2',
    website: 'https://www.wustl.edu',
    motto: 'Per Veritatem Vis (Strength through Truth)',
    vibe: 'Collaborative, resource-rich, balanced, friendly.',
    special: 'Exceptional medical and social work programs; scenic campus.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Washington_University_in_St._Louis_seal.svg',
    ranking: 24,
    majors: [
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Computer Science', category: 'McKelvey Engineering' },
      { name: 'Finance', category: 'Olin Business' },
      { name: 'Political Science', category: 'Arts & Sciences' },
      { name: 'Architecture', category: 'Sam Fox School' }
    ]
  },
  {
    id: 'ucsd',
    name: 'University of California, San Diego',
    type: 'National',
    location: 'La Jolla, CA',
    lat: 32.8801,
    lng: -117.2340,
    sfRatio: 19,
    acceptanceRate: 24,
    undergradEnrollment: 33000,
    totalStudents: 43000,
    tuitionLocal: 15300,
    tuitionIntl: 48000,
    endowment: '2.5',
    website: 'https://www.ucsd.edu',
    motto: 'Fiat Lux (Let There Be Light)',
    vibe: 'Coastal, science-centric, multi-college system, social.',
    special: 'Scripps Institution of Oceanography; seven distinct residential colleges.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/a/ab/UC_San_Diego_seal.svg',
    ranking: 28,
    majors: [
      { name: 'Biology', category: 'Biological Sciences' },
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Cognitive Science', category: 'Social Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Mathematics', category: 'Physical Sciences' }
    ]
  },
  {
    id: 'utaustin',
    name: 'University of Texas at Austin',
    type: 'National',
    location: 'Austin, TX',
    lat: 30.2849,
    lng: -97.7341,
    sfRatio: 18,
    acceptanceRate: 31,
    undergradEnrollment: 41000,
    totalStudents: 52000,
    tuitionLocal: 11700,
    tuitionIntl: 41000,
    endowment: '42.7',
    website: 'https://www.utexas.edu',
    motto: 'Disciplina praesidium civitatis (Cultivated mind is the guardian genius of democracy)',
    vibe: 'Huge, high-energy, weird (Austin!), entrepreneurial.',
    special: 'Hook \'em Horns; top-ranked accounting and business programs; LBJ Library.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e1/University_of_Texas_at_Austin_seal.svg',
    ranking: 32,
    majors: [
      { name: 'Computer Science', category: 'Natural Sciences' },
      { name: 'Business Administration', category: 'McCombs' },
      { name: 'Economics', category: 'Liberal Arts' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Political Science', category: 'Liberal Arts' }
    ]
  },
  {
    id: 'gatech',
    name: 'Georgia Institute of Technology',
    type: 'National',
    location: 'Atlanta, GA',
    lat: 33.7756,
    lng: -84.3963,
    sfRatio: 17,
    acceptanceRate: 16,
    undergradEnrollment: 18000,
    totalStudents: 45000,
    tuitionLocal: 12800,
    tuitionIntl: 33000,
    endowment: '2.5',
    website: 'https://www.gatech.edu',
    motto: 'Progress and Service',
    vibe: 'Tech-intense, engineering-heavy, innovative, urban.',
    special: 'Leading co-op program; strong focus on industrial design and aerospace.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Georgia_Tech_seal.svg',
    ranking: 33,
    majors: [
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Computer Science', category: 'Computing' },
      { name: 'Industrial Engineering', category: 'Engineering' },
      { name: 'Business Administration', category: 'Scheller' },
      { name: 'Electrical Engineering', category: 'Engineering' }
    ]
  },
  {
    id: 'vassar',
    name: 'Vassar College',
    type: 'LAC',
    location: 'Poughkeepsie, NY',
    lat: 41.6883,
    lng: -73.8967,
    sfRatio: 8,
    acceptanceRate: 18,
    undergradEnrollment: 2400,
    totalStudents: 2400,
    tuitionLocal: 64000,
    tuitionIntl: 64000,
    endowment: '1.2',
    website: 'https://www.vassar.edu',
    motto: 'Purity and Wisdom',
    vibe: 'Creative, open-minded, architectural, inclusive.',
    special: 'First women\'s college to go co-ed (1969); arboretum campus.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Vassar_College_seal.svg',
    ranking: 13,
    majors: [
      { name: 'English', category: 'Humanities' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Art History', category: 'Humanities' },
      { name: 'Music', category: 'Arts' },
      { name: 'Astronomy', category: 'Natural Sciences' },
      { name: 'Victorian Studies', category: 'Interdisciplinary' },
      { name: 'Media Studies', category: 'Interdisciplinary' }
    ]
  },
  {
    id: 'unc',
    name: 'University of North Carolina at Chapel Hill',
    type: 'National',
    location: 'Chapel Hill, NC',
    lat: 35.9049,
    lng: -79.0469,
    sfRatio: 13,
    acceptanceRate: 17,
    undergradEnrollment: 20000,
    totalStudents: 31000,
    tuitionLocal: 9000,
    tuitionIntl: 37000,
    endowment: '5.2',
    website: 'https://www.unc.edu',
    motto: 'Lux Libertas (Light and Liberty)',
    vibe: 'Classic Southern collegiate, vibrant, athletic powerhouse.',
    special: 'Oldest public university in the U.S.; top-tier journalism and public health schools.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b1/UNC_Chapel_Hill_seal.svg',
    ranking: 22,
    majors: [
      { name: 'Business Administration', category: 'Kenan-Flagler' },
      { name: 'Journalism', category: 'Hussman Journalism' },
      { name: 'Biology', category: 'College of Arts & Sciences' },
      { name: 'Political Science', category: 'College of Arts & Sciences' },
      { name: 'Public Health', category: 'Gillings School' },
      { name: 'Economics', category: 'College of Arts & Sciences' },
      { name: 'Psychology', category: 'College of Arts & Sciences' },
      { name: 'Computer Science', category: 'College of Arts & Sciences' },
      { name: 'Global Studies', category: 'College of Arts & Sciences' }
    ]
  },
  {
    id: 'ucdavis',
    name: 'University of California, Davis',
    type: 'National',
    location: 'Davis, CA',
    lat: 38.5382,
    lng: -121.7617,
    sfRatio: 20,
    acceptanceRate: 37,
    undergradEnrollment: 31000,
    totalStudents: 40000,
    tuitionLocal: 14500,
    tuitionIntl: 44000,
    endowment: '2.0',
    website: 'https://www.ucdavis.edu',
    motto: 'Fiat Lux (Let There Be Light)',
    vibe: 'Bicycle-friendly, agricultural-meets-tech, friendly, collaborative.',
    special: 'One of the world\'s best veterinary and viticulture programs.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/7/7e/University_of_California%2C_Davis_seal.svg',
    ranking: 28,
    majors: [
      { name: 'Animal Science', category: 'Ag & Env Sciences' },
      { name: 'Viticulture and Enology', category: 'Ag & Env Sciences' },
      { name: 'Biotechnology', category: 'Ag & Env Sciences' },
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Biological Sciences', category: 'Biological Sciences' },
      { name: 'Evolution, Ecology and Biodiversity', category: 'Biological Sciences' },
      { name: 'Managerial Economics', category: 'Ag & Env Sciences' },
      { name: 'Environmental Policy Analysis', category: 'Ag & Env Sciences' }
    ]
  },
  {
    id: 'usc',
    name: 'University of Southern California',
    type: 'National',
    location: 'Los Angeles, CA',
    lat: 34.0224,
    lng: -118.2851,
    sfRatio: 9,
    acceptanceRate: 10,
    undergradEnrollment: 21000,
    totalStudents: 49000,
    tuitionLocal: 66000,
    tuitionIntl: 66000,
    endowment: '7.3',
    website: 'https://www.usc.edu',
    motto: 'Palmam Qui Meruit Ferat (Let him who merited the palm bear it)',
    vibe: 'Ambitious, high-energy, urban, legendary alumni network.',
    special: 'The "Trojan Family"; world-class cinema and business schools.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/a/af/University_of_Southern_California_seal.svg',
    ranking: 28,
    majors: [
      { name: 'Business Administration', category: 'Marshall' },
      { name: 'Cinematic Arts', category: 'SCA' },
      { name: 'Computer Science', category: 'Viterbi Engineering' },
      { name: 'International Relations', category: 'Dornsife' },
      { name: 'Real Estate Development', category: 'Price Public Policy' },
      { name: 'Public Relations', category: 'Annenberg' },
      { name: 'Mechanical Engineering', category: 'Viterbi Engineering' },
      { name: 'Arts, Technology and the Business of Innovation', category: 'Iovine and Young Academy' }
    ]
  },
  {
    id: 'uf',
    name: 'University of Florida',
    type: 'National',
    location: 'Gainesville, FL',
    lat: 29.6436,
    lng: -82.3549,
    sfRatio: 17,
    acceptanceRate: 23,
    undergradEnrollment: 38000,
    totalStudents: 60000,
    tuitionLocal: 6400,
    tuitionIntl: 28000,
    endowment: '2.4',
    website: 'https://www.ufl.edu',
    motto: 'Civium in moribus rei publicae salus (The welfare of the state depends upon the morals of its citizens)',
    vibe: 'Spirited (The Swamp!), public powerhouse, traditional.',
    special: 'Top-ranked online programs; strong athletic tradition (Gators).',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e1/University_of_Florida_seal.svg',
    ranking: 28,
    majors: [
      { name: 'Biology', category: 'Liberal Arts & Sciences' },
      { name: 'Business Administration', category: 'Warrington' },
      { name: 'Psychology', category: 'Liberal Arts & Sciences' },
      { name: 'Mechanical Engineering', category: 'Herbert Wertheim Engineering' },
      { name: 'Political Science', category: 'Liberal Arts & Sciences' },
      { name: 'Nursing', category: 'College of Nursing' },
      { name: 'Agricultural Operations Management', category: 'CALS' },
      { name: 'Telecommunication', category: 'CJC' }
    ]
  },
  {
    id: 'uci',
    name: 'University of California, Irvine',
    type: 'National',
    location: 'Irvine, CA',
    lat: 33.6405,
    lng: -117.8443,
    sfRatio: 18,
    acceptanceRate: 21,
    undergradEnrollment: 28000,
    totalStudents: 36000,
    tuitionLocal: 14000,
    tuitionIntl: 44000,
    endowment: '1.2',
    website: 'https://www.uci.edu',
    motto: 'Fiat Lux (Let There Be Light)',
    vibe: 'Planned, safe, research-focused, suburban-coastal mix.',
    special: 'First university to have a dedicated eSports arena; top computer science.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/52/UCI_seal.svg',
    ranking: 33,
    majors: [
      { name: 'Computer Science', category: 'Donald Bren School' },
      { name: 'Biology / Biological Sciences', category: 'Biological Sciences' },
      { name: 'Psychology', category: 'Social Ecology' },
      { name: 'Business Administration', category: 'Paul Merage Business' },
      { name: 'Criminology, Law and Society', category: 'Social Ecology' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Public Health Policy', category: 'Public Health' },
      { name: 'Games and Interactive Media', category: 'Donald Bren School' }
    ]
  },
  {
    id: 'tufts',
    name: 'Tufts University',
    type: 'National',
    location: 'Medford, MA',
    lat: 42.4085,
    lng: -71.1183,
    sfRatio: 9,
    acceptanceRate: 10,
    undergradEnrollment: 6700,
    totalStudents: 13000,
    tuitionLocal: 66000,
    tuitionIntl: 66000,
    endowment: '2.4',
    website: 'https://www.tufts.edu',
    motto: 'Pax et Lux (Peace and Light)',
    vibe: 'Intellectual, global, quirky, collaborative, civic-minded.',
    special: 'Fletcher School of Law and Diplomacy; proximity to Boston.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Tufts_University_seal.svg',
    ranking: 40,
    majors: [
      { name: 'International Relations', category: 'School of Arts & Sciences' },
      { name: 'Economics', category: 'School of Arts & Sciences' },
      { name: 'Biology', category: 'School of Arts & Sciences' },
      { name: 'Computer Science', category: 'School of Engineering' },
      { name: 'Psychology', category: 'School of Arts & Sciences' },
      { name: 'Biomedical Engineering', category: 'School of Engineering' },
      { name: 'Community Health', category: 'School of Arts & Sciences' },
      { name: 'Peace and Justice Studies', category: 'Interdisciplinary' }
    ]
  },
  {
    id: 'hmc',
    name: 'Harvey Mudd College',
    type: 'LAC',
    location: 'Claremont, CA',
    lat: 34.1061,
    lng: -117.7101,
    sfRatio: 8,
    acceptanceRate: 10,
    undergradEnrollment: 900,
    totalStudents: 900,
    tuitionLocal: 65000,
    tuitionIntl: 65000,
    endowment: '0.4',
    website: 'https://www.hmc.edu',
    motto: 'Innovation, Leadership, and Responsibility',
    vibe: 'Intense, STEM-focused, collaborative, tight community.',
    special: 'Premier STEM-focused liberal arts college; part of the Claremont Colleges.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e5/Harvey_Mudd_College_seal.svg',
    ranking: 16,
    majors: [
      { name: 'Engineering', category: 'Engineering' },
      { name: 'Computer Science', category: 'Computer Science' },
      { name: 'Mathematics', category: 'Mathematics' },
      { name: 'Physics', category: 'Physics' },
      { name: 'Chemistry', category: 'Chemistry' },
      { name: 'Joint Major in Computer Science and Mathematics', category: 'Interdisciplinary' },
      { name: 'Joint Major in Mathematical and Computational Biology', category: 'Interdisciplinary' }
    ]
  },
  {
    id: 'hamilton',
    name: 'Hamilton College',
    type: 'LAC',
    location: 'Clinton, NY',
    lat: 43.0519,
    lng: -75.4079,
    sfRatio: 9,
    acceptanceRate: 14,
    undergradEnrollment: 2000,
    totalStudents: 2000,
    tuitionLocal: 65000,
    tuitionIntl: 65000,
    endowment: '1.3',
    website: 'https://www.hamilton.edu',
    motto: 'Gnothi Seauton (Know Thyself)',
    vibe: 'Open curriculum, communication-focused, rural-scenic, spirited.',
    special: 'The "Open Curriculum"; strong focus on writing and oral communication.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/30/Hamilton_College_seal.svg',
    ranking: 15,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Government', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'World Politics', category: 'Social Sciences' },
      { name: 'Mathematics', category: 'Natural Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Creative Writing', category: 'Humanities' },
      { name: 'Neuroscience', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'colgate',
    name: 'Colgate University',
    type: 'LAC',
    location: 'Hamilton, NY',
    lat: 42.8183,
    lng: -75.5350,
    sfRatio: 9,
    acceptanceRate: 12,
    undergradEnrollment: 3000,
    totalStudents: 3100,
    tuitionLocal: 67000,
    tuitionIntl: 67000,
    endowment: '1.2',
    website: 'https://www.colgate.edu',
    motto: 'Deo ac Veritati (For God and for Truth)',
    vibe: 'Spirited, high-energy, athletic for an LAC, gorgeous campus.',
    special: 'Unique "residential commons" system; strong alumni engagement.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Colgate_University_seal.svg',
    ranking: 18,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'Astrogeophysics', category: 'Natural Sciences' },
      { name: 'Mathematical Economics', category: 'Interdisciplinary' },
      { name: 'Molecular Biology', category: 'Natural Sciences' },
      { name: 'Environmental Studies', category: 'Interdisciplinary' },
      { name: 'Philosophy', category: 'Humanities' },
      { name: 'Physics', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'ucsb',
    name: 'University of California, Santa Barbara',
    type: 'National',
    location: 'Santa Barbara, CA',
    lat: 34.4140,
    lng: -119.8489,
    sfRatio: 17,
    acceptanceRate: 26,
    undergradEnrollment: 23000,
    totalStudents: 26000,
    tuitionLocal: 14400,
    tuitionIntl: 44100,
    endowment: '0.4',
    website: 'https://www.ucsb.edu',
    motto: 'Fiat Lux (Let There Be Light)',
    vibe: 'Coastal, vibrant, research-heavy, social.',
    special: 'Located on a cliff overlooking the Pacific; multiple Nobel laureates in Physics.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/a/a2/University_of_California%2C_Santa_Barbara_seal.svg',
    ranking: 35,
    majors: [
      { name: 'Communication', category: 'Letters & Science' },
      { name: 'Economics', category: 'Letters & Science' },
      { name: 'Psychology', category: 'Letters & Science' },
      { name: 'Biology', category: 'Letters & Science' },
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Physics', category: 'Letters & Science' },
      { name: 'Environmental Studies', category: 'Letters & Science' },
      { name: 'Sociology', category: 'Letters & Science' },
      { name: 'Chemical Engineering', category: 'Engineering' }
    ]
  },
  {
    id: 'uiuc',
    name: 'University of Illinois Urbana-Champaign',
    type: 'National',
    location: 'Urbana, IL',
    lat: 40.1020,
    lng: -88.2272,
    sfRatio: 18,
    acceptanceRate: 45,
    undergradEnrollment: 35000,
    totalStudents: 56000,
    tuitionLocal: 17000,
    tuitionIntl: 36000,
    endowment: '2.6',
    website: 'https://www.illinois.edu',
    motto: 'Learning and Labor',
    vibe: 'Massive, tech-focused, athletic, high-energy.',
    special: 'Grainger College of Engineering is world-renowned; birth of the Mosaic web browser.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/a/af/University_of_Illinois_seal.svg',
    ranking: 35,
    majors: [
      { name: 'Computer Science', category: 'Grainger Engineering' },
      { name: 'Electrical Engineering', category: 'Grainger Engineering' },
      { name: 'Mechanical Engineering', category: 'Grainger Engineering' },
      { name: 'Psychology', category: 'LAS' },
      { name: 'Finance', category: 'Gies Business' },
      { name: 'Accounting', category: 'Gies Business' },
      { name: 'Economics', category: 'LAS' },
      { name: 'Civil Engineering', category: 'Grainger Engineering' },
      { name: 'Agricultural & Biological Engineering', category: 'Grainger Engineering' },
      { name: 'Aerospace Engineering', category: 'Grainger Engineering' }
    ]
  },
  {
    id: 'uwmadison',
    name: 'University of Wisconsin–Madison',
    type: 'National',
    location: 'Madison, WI',
    lat: 43.0766,
    lng: -89.4125,
    sfRatio: 18,
    acceptanceRate: 49,
    undergradEnrollment: 35000,
    totalStudents: 50000,
    tuitionLocal: 11000,
    tuitionIntl: 40000,
    endowment: '3.6',
    website: 'https://www.wisc.edu',
    motto: 'Numen Lumen (The spirit in our hearts is the light of the world)',
    vibe: 'Spirited, scenic (between lakes), academic powerhouse.',
    special: 'Famous for research in genetics and stems cells; beautiful lakeside terrace.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/UW-Madison_seal.svg',
    ranking: 35,
    majors: [
      { name: 'Economics', category: 'Letters & Science' },
      { name: 'Computer Science', category: 'Letters & Science' },
      { name: 'Finance', category: 'School of Business' },
      { name: 'Biology', category: 'Letters & Science' },
      { name: 'Political Science', category: 'Letters & Science' },
      { name: 'Psychology', category: 'Letters & Science' },
      { name: 'History', category: 'Letters & Science' },
      { name: 'Marketing', category: 'School of Business' },
      { name: 'Civil Engineering', category: 'Engineering' }
    ]
  },
  {
    id: 'wesleyan',
    name: 'Wesleyan University',
    type: 'LAC',
    location: 'Middletown, CT',
    lat: 41.5542,
    lng: -72.6568,
    sfRatio: 8,
    acceptanceRate: 14,
    undergradEnrollment: 3000,
    totalStudents: 3200,
    tuitionLocal: 66000,
    tuitionIntl: 66000,
    endowment: '1.5',
    website: 'https://www.wesleyan.edu',
    motto: 'Open for all minds',
    vibe: 'Creative, independent, intellectual, activist.',
    special: 'Strong film and music programs; "The Wes" culture of independence.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f6/Wesleyan_University_seal.svg',
    ranking: 20,
    majors: [
      { name: 'Film Studies', category: 'Arts & Humanities' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'English', category: 'Arts & Humanities' },
      { name: 'Government', category: 'Social Sciences' },
      { name: 'History', category: 'Social Sciences' },
      { name: 'Sociology', category: 'Social Sciences' },
      { name: 'Molecular Biology and Biochemistry', category: 'Sciences' },
      { name: 'Science in Society Program', category: 'Interdisciplinary' }
    ]
  },
  {
    id: 'barnard',
    name: 'Barnard College',
    type: 'LAC',
    location: 'New York, NY',
    lat: 40.8096,
    lng: -73.9631,
    sfRatio: 9,
    acceptanceRate: 8,
    undergradEnrollment: 3000,
    totalStudents: 3000,
    tuitionLocal: 64000,
    tuitionIntl: 64000,
    endowment: '0.4',
    website: 'https://www.barnard.edu',
    motto: 'Hepomene to logism (Following the argument)',
    vibe: 'Empowering, urban, historical, dual-identity (with Columbia).',
    special: 'Women\'s college affiliated with Columbia University; Morningside Heights campus.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/ec/Barnard_College_seal.svg',
    ranking: 17,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'English', category: 'Humanities' },
      { name: 'Political Science', category: 'Social Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'Neuroscience and Behavior', category: 'Natural Sciences' },
      { name: 'Architecture', category: 'Arts' },
      { name: 'Environmental Science', category: 'Natural Sciences' }
    ]
  },
  {
    id: 'uw',
    name: 'University of Washington',
    type: 'National',
    location: 'Seattle, WA',
    lat: 47.6553,
    lng: -122.3035,
    sfRatio: 20,
    acceptanceRate: 48,
    undergradEnrollment: 36000,
    totalStudents: 60000,
    tuitionLocal: 12000,
    tuitionIntl: 40000,
    endowment: '4.7',
    website: 'https://www.washington.edu',
    motto: 'Lux Sit (Let there be light)',
    vibe: 'Pacific Northwest, tech-heavy, outdoorsy, massive.',
    special: 'Leading research in medicine and computer science; beautiful cherry blossoms.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/58/University_of_Washington_seal.svg',
    ranking: 40,
    majors: [
      { name: 'Computer Science', category: 'Paul G. Allen School' },
      { name: 'Informatics', category: 'Information School' },
      { name: 'Bioengineering', category: 'Engineering' },
      { name: 'Psychology', category: 'Arts & Sciences' },
      { name: 'Economics', category: 'Arts & Sciences' },
      { name: 'Business Administration', category: 'Foster School' },
      { name: 'Marine Biology', category: 'Environment' },
      { name: 'Human Centered Design & Engineering', category: 'Engineering' }
    ]
  },
  {
    id: 'bu',
    name: 'Boston University',
    type: 'National',
    location: 'Boston, MA',
    lat: 42.3505,
    lng: -71.1054,
    sfRatio: 10,
    acceptanceRate: 14,
    undergradEnrollment: 18000,
    totalStudents: 36000,
    tuitionLocal: 63000,
    tuitionIntl: 63000,
    endowment: '3.0',
    website: 'https://www.bu.edu',
    motto: 'Learning, Virtue, Piety',
    vibe: 'Urban, international, bustling, professional.',
    special: 'Campus integrated into the city of Boston; strong communications and medical programs.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/da/Boston_University_seal.svg',
    ranking: 43,
    majors: [
      { name: 'Communications', category: 'COM' },
      { name: 'Business Administration', category: 'Questrom' },
      { name: 'Economics', category: 'CAS' },
      { name: 'Psychology', category: 'CAS' },
      { name: 'International Relations', category: 'Pardee' },
      { name: 'Biomedical Engineering', category: 'ENG' },
      { name: 'Hospitality Administration', category: 'SHA' },
      { name: 'Neuroscience', category: 'CAS' }
    ]
  },
  {
    id: 'purdue',
    name: 'Purdue University',
    type: 'National',
    location: 'West Lafayette, IN',
    lat: 40.4237,
    lng: -86.9212,
    sfRatio: 13,
    acceptanceRate: 53,
    undergradEnrollment: 38000,
    totalStudents: 52000,
    tuitionLocal: 10000,
    tuitionIntl: 29000,
    endowment: '3.6',
    website: 'https://www.purdue.edu',
    motto: 'Education, Research, Service',
    vibe: 'Engineering-proud, traditional, midwestern, high-tech.',
    special: 'Cradle of Astronauts; world-class flight and aerospace engineering.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Purdue_University_seal.svg',
    ranking: 43,
    majors: [
      { name: 'Professional Flight', category: 'Polytechnic Institute' },
      { name: 'Aerospace Engineering', category: 'Engineering' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Computer Science', category: 'Science' },
      { name: 'Computer Engineering', category: 'Engineering' },
      { name: 'Industrial Engineering', category: 'Engineering' },
      { name: 'Agribusiness', category: 'Agriculture' },
      { name: 'Cybersecurity', category: 'Polytechnic Institute' }
    ]
  },
  {
    id: 'colby',
    name: 'Colby College',
    type: 'LAC',
    location: 'Waterville, ME',
    lat: 44.5641,
    lng: -69.6629,
    sfRatio: 10,
    acceptanceRate: 7,
    undergradEnrollment: 2200,
    totalStudents: 2200,
    tuitionLocal: 66000,
    tuitionIntl: 66000,
    endowment: '1.2',
    website: 'https://www.colby.edu',
    motto: 'Lux Mentis Scientia (Knowledge is the Light of the Mind)',
    vibe: 'Outdoorsy, northern, creative, rigorous, global.',
    special: 'First LAC to establish an Artificial Intelligence center.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Colby_College_seal.svg',
    ranking: 18,
    majors: [
      { name: 'Environmental Science', category: 'Natural Sciences' },
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Government', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Natural Sciences' },
      { name: 'Biology', category: 'Natural Sciences' },
      { name: 'Global Studies', category: 'Interdisciplinary' },
      { name: 'Art', category: 'Humanities' },
      { name: 'Data Science', category: 'Interdisciplinary' }
    ]
  },
  {
    id: 'osu',
    name: 'Ohio State University',
    type: 'National',
    location: 'Columbus, OH',
    lat: 40.0067,
    lng: -83.0305,
    sfRatio: 18,
    acceptanceRate: 53,
    undergradEnrollment: 47000,
    totalStudents: 61000,
    tuitionLocal: 12500,
    tuitionIntl: 37000,
    endowment: '7.0',
    website: 'https://www.osu.edu',
    motto: 'Disciplina in civitatem (Education for Citizenship)',
    vibe: 'Huge, spirited (Buckeye nation), research-centric, urban.',
    special: 'One of the largest campuses in the U.S.; legendary football culture; Fisher College of Business.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Ohio_State_University_seal.svg',
    ranking: 43,
    majors: [
      { name: 'Finance', category: 'Fisher College of Business' },
      { name: 'Psychology', category: 'Arts & Sciences' },
      { name: 'Computer Science & Engineering', category: 'Engineering' },
      { name: 'Marketing', category: 'Fisher College of Business' },
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Accounting', category: 'Fisher College of Business' },
      { name: 'Communication', category: 'Arts & Sciences' },
      { name: 'Political Science', category: 'Arts & Sciences' }
    ]
  },
  {
    id: 'tamu',
    name: 'Texas A&M University',
    type: 'National',
    location: 'College Station, TX',
    lat: 30.6187,
    lng: -96.3365,
    sfRatio: 19,
    acceptanceRate: 63,
    undergradEnrollment: 57000,
    totalStudents: 75000,
    tuitionLocal: 13000,
    tuitionIntl: 40000,
    endowment: '18.0',
    website: 'https://www.tamu.edu',
    motto: 'None (Values: Excellence, Integrity, Leadership, Loyalty, Respect, Selfless Service)',
    vibe: 'Traditional, polite (Howdy!), spirit-filled, engineering-strong.',
    special: 'Home to the Corps of Cadets; unique traditions; massive engineering program.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/ee/Texas_A%26M_University_seal.svg',
    ranking: 47,
    majors: [
      { name: 'Mechanical Engineering', category: 'College of Engineering' },
      { name: 'Computer Science', category: 'College of Engineering' },
      { name: 'Psychology', category: 'College of Arts & Sciences' },
      { name: 'Business Administration', category: 'Mays Business School' },
      { name: 'Animal Science', category: 'College of Ag & Life Sciences' },
      { name: 'Biomedical Sciences', category: 'Vet Med & Bio Sciences' },
      { name: 'Civil Engineering', category: 'College of Engineering' }
    ]
  },
  {
    id: 'umd',
    name: 'University of Maryland, College Park',
    type: 'National',
    location: 'College Park, MD',
    lat: 38.9869,
    lng: -76.9426,
    sfRatio: 18,
    acceptanceRate: 44,
    undergradEnrollment: 30000,
    totalStudents: 41000,
    tuitionLocal: 11000,
    tuitionIntl: 39000,
    endowment: '2.0',
    website: 'https://www.umd.edu',
    motto: 'Fatti maschii, parole femine (Strong deeds, gentle words)',
    vibe: 'Diverse, urban-adjacent, research-intensive, Terp pride.',
    special: 'Proximity to Washington D.C. and federal agencies; strong focus on cybersecurity.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/3e/University_of_Maryland_seal.svg',
    ranking: 45,
    majors: [
      { name: 'Computer Science', category: 'CMNS' },
      { name: 'Psychology', category: 'BSOS' },
      { name: 'Biological Sciences', category: 'CMNS' },
      { name: 'Finance', category: 'Smith School of Business' },
      { name: 'Economics', category: 'BSOS' },
      { name: 'Mechanical Engineering', category: 'Clark School of Engineering' },
      { name: 'Government and Politics', category: 'BSOS' },
      { name: 'Criminology and Criminal Justice', category: 'BSOS' }
    ]
  },
  {
    id: 'lehigh',
    name: 'Lehigh University',
    type: 'National',
    location: 'Bethlehem, PA',
    lat: 40.6074,
    lng: -75.3788,
    sfRatio: 9,
    acceptanceRate: 37,
    undergradEnrollment: 5400,
    totalStudents: 7200,
    tuitionLocal: 61000,
    tuitionIntl: 61000,
    endowment: '1.6',
    website: 'https://www.lehigh.edu',
    motto: 'Homo Minister et Interpres Naturae (Man, the minister and interpreter of nature)',
    vibe: 'Balanced, engineering-strong, residential, historic.',
    special: 'Strong integration between engineering, business, and arts; scenic hillside campus.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Lehigh_University_seal.svg',
    ranking: 47,
    majors: [
      { name: 'Finance', category: 'College of Business' },
      { name: 'Computer Science', category: 'Engineering / Arts & Sciences' },
      { name: 'Mechanical Engineering', category: 'Rossin Engineering' },
      { name: 'Psychology', category: 'Arts & Sciences' },
      { name: 'Design', category: 'Arts & Sciences' },
      { name: 'Integrated Business and Engineering (IBE)', category: 'Intercollegiate' },
      { name: 'Economics', category: 'College of Business' }
    ]
  },
  {
    id: 'wakeforest',
    name: 'Wake Forest University',
    type: 'National',
    location: 'Winston-Salem, NC',
    lat: 36.1353,
    lng: -80.2790,
    sfRatio: 11,
    acceptanceRate: 21,
    undergradEnrollment: 5400,
    totalStudents: 8900,
    tuitionLocal: 63000,
    tuitionIntl: 63000,
    endowment: '1.6',
    website: 'https://www.wfu.edu',
    motto: 'Pro Humanitate (For Humanity)',
    vibe: 'Small-college feel with big-university resources, rigorous, beautiful.',
    special: 'Famous "Wake Forest" work ethic; top-tier accounting program.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Wake_Forest_University_Seal.svg',
    ranking: 47,
    majors: [
      { name: 'Business & Enterprise Management', category: 'School of Business' },
      { name: 'Economics', category: 'Arts & Sciences' },
      { name: 'Political Science and Government', category: 'Arts & Sciences' },
      { name: 'Psychology', category: 'Arts & Sciences' },
      { name: 'Communication', category: 'Arts & Sciences' },
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Finance', category: 'School of Business' }
    ]
  },
  {
    id: 'vt',
    name: 'Virginia Tech',
    type: 'National',
    location: 'Blacksburg, VA',
    lat: 37.2284,
    lng: -80.4234,
    sfRatio: 14,
    acceptanceRate: 57,
    undergradEnrollment: 30000,
    totalStudents: 38000,
    tuitionLocal: 15500,
    tuitionIntl: 36000,
    endowment: '1.7',
    website: 'https://www.vt.edu',
    motto: 'Ut Prosim (That I May Serve)',
    vibe: 'Community-driven, engineering-excellence, scenic mountains.',
    special: 'Corps of Cadets; legendary food rankings; strong architecture and engineering.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/d7/Virginia_Tech_seal.svg',
    ranking: 47,
    majors: [
      { name: 'Mechanical Engineering', category: 'College of Engineering' },
      { name: 'Computer Science', category: 'College of Engineering' },
      { name: 'Finance', category: 'Pamplin Business' },
      { name: 'Architecture', category: 'CAUS' },
      { name: 'Business Information Technology', category: 'Pamplin Business' },
      { name: 'Psychology', category: 'Science' },
      { name: 'Building Construction', category: 'CAUS' }
    ]
  },
  {
    id: 'uga',
    name: 'University of Georgia',
    type: 'National',
    location: 'Athens, GA',
    lat: 33.9480,
    lng: -83.3773,
    sfRatio: 17,
    acceptanceRate: 43,
    undergradEnrollment: 30000,
    totalStudents: 40000,
    tuitionLocal: 12000,
    tuitionIntl: 31000,
    endowment: '1.8',
    website: 'https://www.uga.edu',
    motto: 'Et docere et rerum exquirere causas (Both to teach and to inquire into the causes of things)',
    vibe: 'Classic Southern college town, high-energy, academic honors-rich.',
    special: 'Terry College of Business; legendary football tradition; historic North Campus.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/University_of_Georgia_seal.svg',
    ranking: 47,
    majors: [
      { name: 'Finance', category: 'Terry Business' },
      { name: 'Psychology', category: 'Arts & Sciences' },
      { name: 'Marketing', category: 'Terry Business' },
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Political Science', category: 'SPIA' },
      { name: 'International Affairs', category: 'SPIA' },
      { name: 'Computer Science', category: 'Computing' }
    ]
  },
  {
    id: 'cwru',
    name: 'Case Western Reserve University',
    type: 'National',
    location: 'Cleveland, OH',
    lat: 41.5042,
    lng: -81.6084,
    sfRatio: 11,
    acceptanceRate: 27,
    undergradEnrollment: 5800,
    totalStudents: 12000,
    tuitionLocal: 62000,
    tuitionIntl: 62000,
    endowment: '2.3',
    website: 'https://www.case.edu',
    motto: 'Think Beyond the Possible',
    vibe: 'Research-heavy, collaborative, innovation-focused, urban.',
    special: 'Strong ties to the Cleveland Clinic; world-renowned program in biomedical engineering.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Case_Western_Reserve_University_seal.svg',
    ranking: 53,
    majors: [
      { name: 'Biomedical Engineering', category: 'Engineering' },
      { name: 'Mechanical Engineering', category: 'Engineering' },
      { name: 'Computer Science', category: 'Engineering' },
      { name: 'Nursing', category: 'FPB Nursing' },
      { name: 'Psychology', category: 'Arts & Sciences' },
      { name: 'Biology', category: 'Arts & Sciences' },
      { name: 'Finance', category: 'Weatherhead Management' }
    ]
  },
  {
    id: 'brandeis',
    name: 'Brandeis University',
    type: 'National',
    location: 'Waltham, MA',
    lat: 42.3650,
    lng: -71.2586,
    sfRatio: 10,
    acceptanceRate: 39,
    undergradEnrollment: 3600,
    totalStudents: 5500,
    tuitionLocal: 62000,
    tuitionIntl: 62000,
    endowment: '1.2',
    website: 'https://www.brandeis.edu',
    motto: 'Truth Even Unto Its Innermost Parts',
    vibe: 'Socially conscious, intellectual, community-oriented.',
    special: 'Strong Jewish heritage and values of social justice; top-tier research in neuroscience.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Brandeis_University_seal.svg',
    ranking: 60,
    majors: [
      { name: 'Economics', category: 'Social Sciences' },
      { name: 'Psychology', category: 'Social Sciences' },
      { name: 'Biology', category: 'Sciences' },
      { name: 'Politics', category: 'Social Sciences' },
      { name: 'Neuroscience', category: 'Sciences' },
      { name: 'History', category: 'Humanities' },
      { name: 'International and Global Studies', category: 'Interdisciplinary' }
    ]
  }
];
